version: '3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    labels:
    # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${SERVICE}.service=api@internal"
      - "traefik.http.routers.${SERVICE}.tls.certresolver=le"
      - "traefik.http.routers.${SERVICE}.entrypoints=web-secure"
# Use Authelia Two-Factor authentication: https://www.authelia.com/docs/
      - "traefik.http.routers.${SERVICE}.middlewares=authelia@file"
      - "traefik.http.middlewares.${SERVICE}_https.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE}_redirect.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.${SERVICE}_redirect.entrypoints=web"
      - "traefik.http.routers.${SERVICE}_redirect.middlewares=${SERVICE}_https"
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - "./acme.json:/acme.json"
      - ./traefik_config:/traefik_config
    networks:
      - web
networks:
  web:
    external: true
