# Refer to https://docs.traefik.io/reference/static-configuration/file/
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

# https://docs.traefik.io/observability/logs
[log]
#  level = "DEBUG"

# https://docs.traefik.io/observability/access-logs/#access-logs
[accessLog]
  bufferingSize = 42
#  filePath = "/dev/stdout"
#  format = "json"

# Minitoring with https://prometheus.io
#[metrics]
#  [metrics.prometheus]
#    addEntryPointsLabels = true
#    addServicesLabels = true
#    buckets = [0.1,0.3,1.2,5.0]

# Retry failed requests three times
# https://docs.traefik.io/middlewares/retry/#retry
[http.middlewares]
  [http.middlewares.test-retry.retry]
     attempts = 4

[api]
  insecure = true
  dashboard = true
  debug = true

[providers]
  [providers.docker]
    exposedByDefault = false
    watch = true
  #  useBindPortIP = true
    network = "web"

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.le.acme]
    email = "email@example.com"
    storage = "acme.json"
    [certificatesResolvers.le.acme.httpChallenge]
      # used during the challenge
      entryPoint = "web"
  #    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
    [certificatesResolvers.le.acme.tlsChallenge]

# Uncomment fot Aauthelia
# More info https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html
#[providers]
#  [providers.file]
#    directory = "/traefik_config"
#    watch = true
